config/routes.rb
Rails.application.routes.draw do

  resources :objective_images
  resources :drag_drops
  resources :subjective_textuals
  resources :objective_textuals
  resources :line_badges do
    collection do
      post :badge_wall_share
    end
  end

  resources :badges
  resources :done_lessons
  get 'admin/index'
  get 'admin/new_token'
  get 'admin/delete_token'

  resources :line_items
  resources :inventories
  get 'store/index'

  resources :items
  resources :characters do
    collection do
      post :addItem
      post :removeItem
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :questions
    end
  end

  resources :lessons
  resources :store

  get 'main/index'

  get 'quiz/index'

  get 'quiz/gerar_quiz'

  get 'quiz/catalog'

  resources :quiz do
    collection do
      post :answer
      post 'answer_question'
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  resources :questions

  root 'main#index'

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
    before_create :generate_access_token

    private

    def generate_access_token
        begin
            self.access_token = SecureRandom.hex
        end while self.class.exists?(access_token: access_token)
    end
end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :User
  validates :name, presence:true

    def add_item(item_name, item_img, item_part)
        if item_part == "helmet"
            self.helmet = item_img
        elsif item_part == "shield"
            self.shield = item_img
        elsif item_part == "weapon"
            self.weapon = item_img
        elsif item_part == "armor"
            self.armor = item_img
        end
    end

    def remove_item(item_part)
        if item_part == "helmet"
            self.helmet = "none"
        elsif item_part == "shield"
            self.shield = "none"
        elsif item_part == "weapon"
            self.weapon = "none"
        elsif item_part == "armor"
            self.armor = "none"
        end
    end

end

app/models/done_lesson.rb
class DoneLesson < ActiveRecord::Base
  belongs_to :Lesson
  belongs_to :Character
end

app/models/drag_drop.rb
class DragDrop < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	private
	def ensure_not_referenced_by_any_line_item
	if line_items.empty?
	return true
	else
	errors.add(:base, 'Line Items present')
	return false
	end
	end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
      public
      def youtubeRegExp(url)
        url.match(/(youtu\.be\/|youtube\.com\/(watch\?(.*&)?v=|(embed|v)\/))([^\?&"'>]+)/)[5]
      end
end

app/models/line_badge.rb
class LineBadge < ActiveRecord::Base
  belongs_to :badge
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :inventory
end

app/models/objective_image.rb
class ObjectiveImage < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :inventory
	has_many :line_badges
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :timeoutable, :registerable

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.where(user_id: current_user)
    if @character != nil
      @inventories = Inventory.where(user_id: current_user)
      @line_items = @inventories.first.line_items
    end
  end

  def addItem
    @character = Character.where(user_id: current_user).first
    @inventories = Inventory.where(user_id: current_user)
    @line_items = @inventories.first.line_items
    @item_img = params[:item_img]
    @item_part = params[:part]
    @character.add_item(params[:name], params[:item_img], params[:part])
    if @character.save
       respond_to do |format|
          format.js
      end
    end
  end

  def removeItem
    @character = Character.where(user_id: current_user).first
    @inventories = Inventory.where(user_id: current_user)
    @line_items = @inventories.first.line_items
    @character.remove_item(params[:part])
    if @character.save
      respond_to do |format|
          format.js
      end
     end
  end
  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @characters = Character.where(user_id: current_user)
    if(@characters.size >= 1)
      redirect_to characters_url
    else
      @character = Character.new
    end
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @inventory = Inventory.new
    @inventory.user_id = current_user.id
    @character = Character.new(character_params)
    @character.user_id = current_user.id
    @character.level = 1
    @character.xp = 0
    @character.gold = 200
    @character.helmet = "none"
    @character.armor = "none"
    @character.weapon = "none"
    @character.shield = "none"
    @character.wrong = 0
    @character.correct = 0
    respond_to do |format|
      if @character.save && @inventory.save
        format.html { redirect_to characters_url, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @done_lessons = DoneLesson.where(character_id: @character.id)
    @done_lessons.each do |done_lesson|
      done_lesson.destroy
    end
    @character.destroy
    @inventories = Inventory.where(user_id: current_user)
    @inventories.each do |inventory|
      inventory.destroy
    end
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :xp, :gold, :hair, :skin, :shirt, :pants, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :xp %><br>
    <%= f.number_field :xp %>
  </div>
  <div class="field">
    <%= f.label :gold %><br>
    <%= f.number_field :gold %>
  </div>
  <div class="field">
    <%= f.label :hair %><br>
    <%= f.text_field :hair %>
  </div>
  <div class="field">
    <%= f.label :skin %><br>
    <%= f.text_field :skin %>
  </div>
  <div class="field">
    <%= f.label :shirt %><br>
    <%= f.text_field :shirt %>
  </div>
  <div class="field">
    <%= f.label :pants %><br>
    <%= f.text_field :pants %>
  </div>
  <div class="field">
    <%= f.label :User_id %><br>
    <%= f.text_field :User_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/addItem.js.erb
$('#list').html('<%= escape_javascript render (@line_items) %>');
$('#canvasDiv').empty();
prepareCanvas(document.getElementById("canvasDiv"), 490, 220, "<%= @character.helmet%>", "<%= @character.armor%>", "<%= @character.shield%>", "<%= @character.weapon%>");
                change('hair', "<%= @character.hair %>");
                change('torso', "<%= @character.shirt %>");
                change('legs', "<%= @character.pants %>");
                if("<%= @character.skin %>" != "default"){
                  change('head', "head_" + "<%= @character.skin %>");
                  change('leftArm', "leftArm_" + "<%= @character.skin %>");
                  change('rightArm', "rightArm_" + "<%= @character.skin %>");
                }

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<%= render :partial => 'layouts/masthead' %>
<section class="no_padding main">
  <div class="container">
    <h1 class="post_title entry-title">Seu Personagem</h1>
    <div class="sc_line sc_line_style_dashed"></div>
    <div class="post_text_area">
      <div class="columnsWrap sc_columns no_margin sc_columns_count_4 margin_top_small">
        <%if @characters.size >= 1%>
          <% @characters.each do |character| %>
            <div class="columns1_4 sc_column_item sc_column_item_1 odd first">
              <h2><%= character.name %></h2>
              <h3>Level: <%= character.level %></h3>
              <h3>xp: <%= character.xp %></h3>
              <h3>Gold: <%= character.gold %></h3>
            </div>
            <div class="columns1_4 sc_column_item sc_column_item_4 even after_span_2">
              <h3>Inventario: </h3>
              <%= link_to image_tag("bag.png", :width =>160, :border => 0, :class => 'list_image'), inventories_url %>
            </div>
            <div class="columns2_4 sc_column_item sc_column_item_2 even span_2">
              <div id="canvasDiv"></div>
              <script type="text/javascript">
                prepareCanvas(document.getElementById("canvasDiv"), 490, 220, "<%= @character.helmet%>", "<%= @character.armor%>", "<%= @character.shield%>", "<%= @character.weapon%>");
                change('hair', "<%= character.hair %>");
                change('torso', "<%= character.shirt %>");
                change('legs', "<%= character.pants %>");
                if("<%= character.skin %>" != "default"){
                  change('head', "head_" + "<%= character.skin %>");
                  change('leftArm', "leftArm_" + "<%= character.skin %>");
                  change('rightArm', "rightArm_" + "<%= character.skin %>");
                }
              </script>

            </div>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Item</th>
      <th>Preço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id ="list">
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.item.name %></td>
        <td><%= image_tag(line_item.item.img, class: 'list_image') %></td>
        <td><%= line_item.item.price %></td>
        <% if (line_item.item.img == @character.helmet || line_item.item.img == @character.armor || line_item.item.img == @character.weapon || line_item.item.img == @character.shield) %>
          <td><%= button_to 'Desequipar', {:controller => "characters", :action => "removeItem", :part => line_item.item.part} , class: "btn btn-warning", :remote => :true %></td>
        <% else %>
          <td><%= button_to 'Equipar', {:controller => "characters", :action => "addItem", :name => line_item.item.name,:item_img => line_item.item.img, :part => line_item.item.part} , class: "btn btn-primary pull-left", :remote => :true %></td>
          <td><%= button_to 'Vender', line_item, method: :delete, class: "btn btn-success pull-right", data: { confirm: 'Tem certeza que deseja vender?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
            <br>
            <br>
            <div class="sc_button sc_button_style_dark  sc_button_size_mini squareButton fullSize dark  mini  ico margin_bottom_mini" >
              <%= link_to 'Deletar Personagem', character, method: :delete, data: { confirm: 'Cuidado, tem certeza que quer deletar seu personagem?' }, class: "" %>
            </div>
          <% end %>
        <% else %>
        <div class="columns4_4">
          <h2>Voce ainda não tem um personagem</h2>
          <%= link_to 'Criar Personagem', new_character_path %>
        </div>
        <% end %>
        <div class="columns4_4">

        </div>
      </div>

        <div class="sc_line sc_line_style_dashed"></div>

    </div> <!-- /post_text_area-->
  </div> <!-- /container -->
</section>

app/views/characters/new.html.erb
<section class="no_padding main">
  <div class="content">
    <section class="post post_format_standard postAlter page type-page">
      <article class="post_content">
        <div class="post_text_area">

          <section class="no_padding">
            <div class="container">


              <%= form_for(@character) do |f| %>
              <div class="post_text_area">


                <div class="columnsWrap sc_columns no_margin sc_columns_count_4 margin_top_small">
                  <div class="columns1_4 sc_column_item sc_column_item_1 odd first align_center ">
                    <div class="columnsWrap">
                      <div class="columns3_3">
                       <h3>Novo personagem</h3>
                        <%= f.label :Nome %> <%= f.text_field :name, :class => ''%>
                      </div>
                    </div>


                      <style>
                        #canvas {
                          margin-left: -160px;
                          margin-top: 10px;
                        }
                      </style>
                    <div id="canvasDiv"></div>
                    <script type="text/javascript">
                      prepareCanvas(document.getElementById("canvasDiv"), 390, 220, "none", "none", "none", "none");
                    </script>

                    <br>
                    <br>
                    <br>
                    <div class="sc_line sc_line_style_dashed"></div>
                    <div class="sc_button sc_button_style_global sc_button_size_huge squareButton fullSize global huge  ico margin_bottom_mini">
                      <%= f.submit "Criar Personagem", :class=>""%>
                    </div>

                    <div class="sc_line sc_line_style_dashed"></div>
                  </div> <!-- /columns1_4 sc_column_item sc_column_item_1 odd first -->
                  <div class="columns3_4 sc_column_item sc_column_item_2 even span_3">
                    <h2 class="sc_title sc_title_regular aligncenter margin_bottom_small">Características</h2>
                    <div class="sc_pricing_table columns_4 alignCenter">
                      <div class="sc_pricing_columns sc_pricing_column_1">
                        <ul class="columnsAnimate">
                          <li class="sc_pricing_data sc_pricing_title"><%= image_tag  "sm_hair.png", :class =>"media-left"%></li>
                          <li class="sc_pricing_data sc_pricing_price">
                            <div class="sc_price_item">
                              <div class="sc_price_money">Cabelo</div>

                            </div>
                          </li>
                          <li class="sc_pricing_data"><%= f.radio_button :hair, 'hair', onClick: "change('hair', 'hair');", :checked => true %><%= label :hair_default, 'Default'%></li>
                          <li class="sc_pricing_data"><%= f.radio_button :hair, 'hair_green', onClick: "change('hair','hair_green');" %><%= label :hair_green, 'Green' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :hair, 'hair_pink', onClick: "change('hair','hair_pink');"%><%= label :hair_blue, 'Pink' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :hair, 'hair_red', onClick: "change('hair','hair_red');" %><%= label :hair_brown, 'Red' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :hair, 'hair_yellow', onClick: "change('hair','hair_yellow');" %><%= label :hair_yellow, 'yellow' %></li>
                        </ul>
                      </div>
                      <div class="sc_pricing_columns sc_pricing_column_2">
                        <ul class="columnsAnimate">
                          <li class="sc_pricing_data sc_pricing_title"><%= image_tag  "sm_torso.png", :class =>"media-left"%></li>
                          <li class="sc_pricing_data sc_pricing_price">
                            <div class="sc_price_item">
                              <div class="sc_price_money">Tronco</div>
                            </div>
                          </li>
                          <li class="sc_pricing_data"><%= f.radio_button :shirt, 'torso', onClick: "change('torso', 'torso');", :checked => true %><%= label :torso, 'Default'%></li>
                          <li class="sc_pricing_data"><%= f.radio_button :shirt, 'torso_blue', onClick: "change('torso','torso_blue');" %><%= label :shirt_blue, 'Blue' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :shirt, 'torso_gray', onClick: "change('torso','torso_gray');"%><%= label :shirt_gray, 'Gray' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :shirt, 'torso_purple', onClick: "change('torso','torso_purple');" %><%= label :shirt_purple, 'Purple' %></li>
                        </ul>
                      </div>
                      <div class="sc_pricing_columns sc_pricing_column_3">
                        <ul class="columnsAnimate">
                          <li class="sc_pricing_data sc_pricing_title"><%= image_tag  "sm_head.png", :class =>"media-left"%></li>
                          <li class="sc_pricing_data sc_pricing_price">
                            <div class="sc_price_item">
                              <div class="sc_price_money">Cabeça</div>
                            </div>
                          </li>
                          <li class="sc_pricing_data"><%= f.radio_button :skin, 'default', onClick: "change('head', 'head');change('leftArm', 'leftArm');change('rightArm', 'rightArm');", :checked => true %><%= label :skin, 'Default'%></li>
                          <li class="sc_pricing_data"><%= f.radio_button :skin, 'green', onClick: "change('head', 'head_green');change('leftArm', 'leftArm_green');change('rightArm', 'rightArm_green');" %><%= label :skin, 'Green' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :skin, 'pink', onClick: "change('head', 'head_pink');change('leftArm', 'leftArm_pink');change('rightArm', 'rightArm_pink');"%><%= label :skin, 'Pink' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :skin, 'yellow', onClick: "change('head', 'head_yellow');change('leftArm', 'leftArm_yellow');change('rightArm', 'rightArm_yellow');" %><%= label :skin, 'Yellow' %></li>
                        </ul>
                      </div>
                      <div class="sc_pricing_columns sc_pricing_column_4">
                        <ul class="columnsAnimate">
                          <li class="sc_pricing_data sc_pricing_title"><%= image_tag  "sm_legs.png", :class =>"media-left"%></li>
                          <li class="sc_pricing_data sc_pricing_price">
                            <div class="sc_price_item">
                              <div class="sc_price_money">Calça</div>
                            </div>
                          </li>
                          <li class="sc_pricing_data"><%= f.radio_button :pants, 'legs', onClick: "change('legs', 'legs');", :checked => true %><%= label :pants, 'Default'%></li>
                          <li class="sc_pricing_data"><%= f.radio_button :pants, 'legs_gray', onClick: "change('legs', 'legs_gray');" %><%= label :pants, 'Gray' %></li>
                          <li class="sc_pricing_data"><%= f.radio_button :pants, 'legs_green', onClick: "change('legs', 'legs_green');"%><%= label :skin, 'Green' %></li>
                        </ul>
                      </div>
                    </div>
                    <br>
                  </div> <!-- /columns3_4 sc_column_item sc_column_item_2 even span_3 -->
                </div> <!-- /columnsWrap sc_columns no_margin sc_columns_count_4 margin_top_small -->
                <div class="sc_line sc_line_style_solid margin_top_big margin_bottom_big"></div>



              </div> <!-- /.post_text_area -->
              <% end %>
            </div>
          </section>

        </div>
      </article>
    </section>
  </div>
</section>






    <div class="col-md-7">

    </div>

app/views/characters/removeItem.js.erb
$('#list').html('<%= escape_javascript render (@line_items) %>');
$('#canvasDiv').empty();
prepareCanvas(document.getElementById("canvasDiv"), 490, 220, "<%= @character.helmet%>", "<%= @character.armor%>", "<%= @character.shield%>", "<%= @character.weapon%>");
                change('hair', "<%= @character.hair %>");
                change('torso', "<%= @character.shirt %>");
                change('legs', "<%= @character.pants %>");
                if("<%= @character.skin %>" != "default"){
                  change('head', "head_" + "<%= @character.skin %>");
                  change('leftArm', "leftArm_" + "<%= @character.skin %>");
                  change('rightArm', "rightArm_" + "<%= @character.skin %>");
                }

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Xp:</strong>
  <%= @character.xp %>
</p>

<p>
  <strong>Gold:</strong>
  <%= @character.gold %>
</p>

<p>
  <strong>Hair:</strong>
  <%= @character.hair %>
</p>

<p>
  <strong>Skin:</strong>
  <%= @character.skin %>
</p>

<p>
  <strong>Shirt:</strong>
  <%= @character.shirt %>
</p>

<p>
  <strong>Pants:</strong>
  <%= @character.pants %>
</p>

<p>
  <strong>User:</strong>
  <%= @character.User %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>